{% set version = "0.0.76" %}

package:
  name: mcstasscript
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mcstasscript/mcstasscript-{{ version }}.tar.gz
  sha256: 4733f5a46b329813f3935dea673508b845cae0abd2437bd033839e11f4c49328

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - pyyaml
    - ipywidgets
    - libpyvinyl
    - ipympl
    - h5py

test:
  imports:
    - mcstasscript
  commands:
    - pip check
    - pytest mcstasscript/tests
  source_files:
    - mcstasscript
  requires:
    - pytest
    - pip
    - python {{ python_min }}

about:
  home: https://mads-bertelsen.github.io/
  summary: McStas API for creating and running McStas instruments from python scripting
  description: |
    McStasScript is a Python API for McStas, which allows the user to get help,
    build their instrument, perform simulations and plot the resulting
    data. This site serves as the documentation for the package and contains
    conceptual explanations of how the package is meant to be used, tutorials
    and a reference for all internal functions/methods.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://mads-bertelsen.github.io/
  dev_url: https://github.com/PaNOSC-ViNYL/McStasScript

extra:
  recipe-maintainers:
    - mads-bertelsen
    - willend
    - tkittel
